//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger_v2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDistributer
    {
        public int DID { get; set; }
        public System.DateTime Distributetime { get; set; }
        public string Location { get; set; }
        public int Distributednumber { get; set; }
        public string notes { get; set; }
        public int RID { get; set; }
        public int EmpID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FoodCollection FoodCollection { get; set; }
    }
}
